### ISSUE TITLE
version incorrect

### ISSUE THREAD

**Issue by robhafner** [sassoftware/gotagger#12]
**Describe the bug**
gotagger isn't correctly identifying that a commit affects more than one module. This lead to a patch bump in a release instead of a minor bump even though a a feature change occurred since the last release. 

**Expected behavior**
Minor bump in a release.

**Comment by wfscheper** [comment]
@robhafner, could you verify the linked PR fixes your issue?

I think the command should be:
`go mod edit -replace github.com/sassoftware/gotagger=github.com/wfscheper/gotagger@wfscheper/issue12`
